/* Builds the app in two steps.

   First kasse.html is assembled from the parts under src/. That single
   file is what the register actually runs: opened from a USB stick over
   file://, a browser refuses to pull in separate stylesheets and modules,
   so everything has to arrive in one document.

   Then public/ is built from it, adding what makes the hosted copy
   installable. Both kasse.html and public/ are generated and must not be
   edited by hand; src/ is where the app is edited. */
import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";

const SRC = "src";
const SINGLE = "kasse.html";
const OUT = "public";

/* A line that is nothing but a comment holding "@include <path>" is
   replaced by that file, verbatim. Written as a comment in each language
   so the skeleton stays valid HTML, CSS and JavaScript on its own. */
const INCLUDE = /^[ \t]*(?:\/\*|\/\/|<!--)\s*@include\s+(\S+).*\r?\n/gm;

/* Says where the file came from, for anyone who opens kasse.html itself
   and starts editing. It is not in the repository, so a stray edit would
   otherwise go unnoticed until the next build silently undid it. */
const NOTICE = "<!-- Generated by build.mjs from src/. Edits here are lost on the next build. -->\n";

let included = 0;
const source = readFileSync(join(SRC, "index.html"), "utf8")
  .replace(INCLUDE, (_, file) => {
    included++;
    return readFileSync(join(SRC, file), "utf8");
  })
  .replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + NOTICE);
if (!included) throw new Error("no @include markers in " + SRC + "/index.html");
if (!source.includes(NOTICE)) throw new Error("could not place the generated-file notice");
writeFileSync(SINGLE, source);

/* The app carries its own version: it is shown in the settings and printed
   under every report, and it has to be readable offline, so it lives in the
   source rather than being injected at build time. package.json has to agree
   with it, otherwise a release would be tagged with a number the register
   never shows. */
const version = source.match(/const VERSION\s*=\s*"([^"]+)"/)?.[1];
if (!version) throw new Error("no VERSION constant in " + SRC + "/js/constants.js");
const declared = JSON.parse(readFileSync("package.json", "utf8")).version;
if (declared !== version) {
  throw new Error(`version mismatch: package.json says ${declared}, the app says ${version}`);
}

/* The mark already sits in the source as a data URI. Pull it back out so the
   manifest can point at a real file instead of duplicating the bytes. */
const favicon = source.match(/<link rel="icon" type="image\/svg\+xml" href="(data:image\/svg\+xml,[^"]+)">/);
if (!favicon) throw new Error("svg favicon not found in " + SINGLE);
const iconSvg = decodeURIComponent(favicon[1].slice("data:image/svg+xml,".length));

const icon192 = readFileSync("assets/icon-192.png");
const icon512 = readFileSync("assets/icon-512.png");

/* Stamp taken from the source, not from the finished page, so it can be
   written into that page. It names the service worker cache and is shown
   in the settings, which is the only way to tell from the outside whether
   a device is looking at a fresh copy or at one out of its cache. */
const stamp = createHash("sha256")
  .update(source).update(icon192).update(icon512).update(iconSvg)
  .digest("hex").slice(0, 12);

/* index.html: the source plus the things that make it installable. */
const injected = `
<meta name="build" content="${stamp}">
<link rel="manifest" href="/manifest.webmanifest">
<script>
/* The service worker is what keeps the register usable when the hut's
   connection gives out mid-shift. */
if ("serviceWorker" in navigator) {
  addEventListener("load", () => navigator.serviceWorker.register("/sw.js"));
}
</script>
`;
const index = source.replace("</head>", injected + "</head>");
if (index === source) throw new Error("could not inject into <head>");

const manifest = {
  name: "KNYL Hüttenkasse",
  short_name: "Hüttenkasse",
  description: "Kassensystem für das Hüttenfest",
  lang: "de",
  start_url: "/",
  scope: "/",
  display: "fullscreen",
  display_override: ["fullscreen", "standalone", "minimal-ui"],
  orientation: "any",
  background_color: "#1b1714",
  theme_color: "#1b1714",
  icons: [
    { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    { src: "/icon-mark.svg", sizes: "any", type: "image/svg+xml", purpose: "any" }
  ]
};

const sw = `/* Generated by build.mjs. Do not edit.
   Cache-first: once a tablet holds the app, a flaky connection cannot take
   it away. A new deploy is fetched quietly in the background and takes over
   on the next start, so no shift is interrupted by an update. */
const CACHE = "huettenkasse-${stamp}";
// "/index.html" is deliberately absent: the host redirects it to "/", and a
// redirected response cannot be pre-cached. "/" is what navigations ask for.
const ESSENTIAL = "/";
const EXTRAS = ["/manifest.webmanifest", "/icon-192.png", "/icon-512.png", "/icon-mark.svg"];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // The page itself has to be there. Icons failing must not sink the install,
    // otherwise a single hiccup leaves the tablet with no offline copy at all.
    await cache.add(ESSENTIAL);
    await Promise.allSettled(EXTRAS.map(url => cache.add(url)));
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  // Cloudflare's own endpoints, injected into the page by Bot Fight Mode.
  // They carry one-time tokens, so a cached copy is worthless, and offline
  // they would be answered with our plain text notice instead of a script.
  if (url.pathname.startsWith("/cdn-cgi/")) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });

    const fresh = fetch(req)
      .then(res => {
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      })
      .catch(() => null);

    // Keep the worker alive long enough to finish the background refresh.
    event.waitUntil(fresh);

    if (hit) return hit;
    return (await fresh) || new Response(
      "Kasse ist offline und noch nicht auf diesem Gerät gespeichert.",
      { status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } }
    );
  })());
});
`;

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
writeFileSync(`${OUT}/index.html`, index);
writeFileSync(`${OUT}/manifest.webmanifest`, JSON.stringify(manifest, null, 2));
writeFileSync(`${OUT}/sw.js`, sw);
copyFileSync("assets/icon-192.png", `${OUT}/icon-192.png`);
copyFileSync("assets/icon-512.png", `${OUT}/icon-512.png`);
writeFileSync(`${OUT}/icon-mark.svg`, iconSvg);

console.log(`built ${SINGLE} from ${SRC}/ (${included} parts) and ${OUT}/  (app ${version}, cache ${stamp})`);
