/* Builds the hosted version from the single-file source.
   kasse.html stays the one place where the app is edited; everything
   under public/ is generated and must not be edited by hand. */
import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync } from "node:fs";
import { createHash } from "node:crypto";

const SRC = "kasse.html";
const OUT = "public";

const source = readFileSync(SRC, "utf8");
const version = source.match(/const VERSION\s*=\s*"([^"]+)"/)?.[1] ?? "0";

/* The mark already sits in the source as a data URI. Pull it back out so the
   manifest can point at a real file instead of duplicating the bytes. */
const favicon = source.match(/<link rel="icon" type="image\/svg\+xml" href="(data:image\/svg\+xml,[^"]+)">/);
if (!favicon) throw new Error("svg favicon not found in " + SRC);
const iconSvg = decodeURIComponent(favicon[1].slice("data:image/svg+xml,".length));

/* index.html: the source plus the two things that make it installable. */
const injected = `
<link rel="manifest" href="/manifest.webmanifest">
<script>
/* The service worker is what keeps the register usable when the hut's
   connection gives out mid-shift. */
if ("serviceWorker" in navigator) {
  addEventListener("load", () => navigator.serviceWorker.register("/sw.js"));
}
</script>
`;
const index = source.replace("</head>", injected + "</head>");
if (index === source) throw new Error("could not inject into <head>");

const icon192 = readFileSync("assets/icon-192.png");
const icon512 = readFileSync("assets/icon-512.png");

/* Cache name derived from content, so each deploy invalidates exactly once. */
const stamp = createHash("sha256")
  .update(index).update(icon192).update(icon512).update(iconSvg)
  .digest("hex").slice(0, 12);

const manifest = {
  name: "KNYL Hüttenkasse",
  short_name: "Hüttenkasse",
  description: "Kassensystem für das Hüttenfest",
  lang: "de",
  start_url: "/",
  scope: "/",
  display: "fullscreen",
  display_override: ["fullscreen", "standalone", "minimal-ui"],
  orientation: "any",
  background_color: "#1b1714",
  theme_color: "#1b1714",
  icons: [
    { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    { src: "/icon-mark.svg", sizes: "any", type: "image/svg+xml", purpose: "any" }
  ]
};

const sw = `/* Generated by build.mjs. Do not edit.
   Cache-first: once a tablet holds the app, a flaky connection cannot take
   it away. A new deploy is fetched quietly in the background and takes over
   on the next start, so no shift is interrupted by an update. */
const CACHE = "huettenkasse-${stamp}";
// "/index.html" is deliberately absent: the host redirects it to "/", and a
// redirected response cannot be pre-cached. "/" is what navigations ask for.
const ESSENTIAL = "/";
const EXTRAS = ["/manifest.webmanifest", "/icon-192.png", "/icon-512.png", "/icon-mark.svg"];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // The page itself has to be there. Icons failing must not sink the install,
    // otherwise a single hiccup leaves the tablet with no offline copy at all.
    await cache.add(ESSENTIAL);
    await Promise.allSettled(EXTRAS.map(url => cache.add(url)));
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });

    const fresh = fetch(req)
      .then(res => {
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      })
      .catch(() => null);

    // Keep the worker alive long enough to finish the background refresh.
    event.waitUntil(fresh);

    if (hit) return hit;
    return (await fresh) || new Response(
      "Kasse ist offline und noch nicht auf diesem Gerät gespeichert.",
      { status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } }
    );
  })());
});
`;

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
writeFileSync(`${OUT}/index.html`, index);
writeFileSync(`${OUT}/manifest.webmanifest`, JSON.stringify(manifest, null, 2));
writeFileSync(`${OUT}/sw.js`, sw);
copyFileSync("assets/icon-192.png", `${OUT}/icon-192.png`);
copyFileSync("assets/icon-512.png", `${OUT}/icon-512.png`);
writeFileSync(`${OUT}/icon-mark.svg`, iconSvg);

console.log(`built ${OUT}/ from ${SRC}  (app ${version}, cache ${stamp})`);
